export const HIERARCHY_TYPE_REPOSITORY = Symbol('HIERARCHY_TYPE_REPOSITORY');
export const WORK_TYPE_REPOSITORY = Symbol('WORK_TYPE_REPOSITORY');
export const PERMISSION_REPOSITORY = Symbol('PERMISSION_REPOSITORY');
export const ROLE_REPOSITORY = Symbol('ROLE_REPOSITORY');
